language: c
compiler: gcc
script:
  - $CC -c rle.c -o rle.o
  - ar rcs librle.a rle.o
  - $CC -coverage unit_tests.c -o unit_tests
  - time ./unit_tests
  - gcov rle.c
after_success:
  - bash <(curl -s https://codecov.io/bash)