language: c
compiler: gcc
script:
  - $CC -c src/rle.c -o rle.o
  - ar rcs librle.a rle.o
  - $CC -coverage src/tests.c
  - time ./a.out
  - gcov src/rle.c
after_success:
  - bash <(curl -s https://codecov.io/bash)